### ISSUE TITLE
Is it possible to change the underlying theme colors?

### ISSUE THREAD

**Issue by mainrs** [catppuccin/nix#254] opened 2024-06-28 21:41 UTC
Let's say I want to change some colors of the underlying catppuccin theme. Can this be done with the nix module in such a way that I declare my changes once (somewhere), and all the nix-defined modules pick up my change?

I took a look at the code, but I couldn't find the location of the code that is responsible for actually importing the catppuccin theme colors. Or generating them.

**Comment by isabelroses** [comment] 2024-06-28 21:54
Only a small number of themes are generated here, one example being [`console.colors`](https://github.com/catppuccin/nix/blob/main/modules/nixos/console.nix). Otherwise everything else is imported via [npins](https://github.com/catppuccin/nix/blob/main/.sources/sources.json). If you want to you can also bring your own sources via [catppuccin.sources](https://nix.catppuccin.com/options/nixos-options.html#catppuccinsources), which maybe useful for fixing themes.

**Comment by mainrs** [comment] 2024-06-28 21:58
> If you want to you can also bring your own sources via [catppuccin.sources](https://nix.catppuccin.com/options/nixos-options.html#catppuccinsources), which maybe useful for fixing themes.

Could you help me out on what this means exactly, please?

**Comment by isabelroses** [comment] 2024-06-28 22:10
So the `catppuccin.sources` option provides catppuccin/nix with all the catppuccin ports that it need to function and apply. For example you find something wrong with [gh-dash](https://github.com/catppuccin/nix/blob/63e0859743908a53e58b3ceeca06a145a45c4435/modules/home-manager/gh-dash.nix) and you make that change to upstream. You may not want to wait for it to get merged before it gets fixed. So you can do 
```nix
{
  catppuccin.sources."gh-dash" = pkgs.fetchFromGitHub {
    owner = "you";
    repo = "gh-dash";
    rev = "rev";
    hash = "hash";
  };
}
```
To "override" the original source.

**Comment by getchoo** [comment] 2024-06-29 01:46
duplicate of #148

as isabel mentioned, a possible workaround for this is `catppuccin.sources` - though this interface is not considered stable and may break at any time. other than that, this is not going to be implemented as these modules are meant to showcase only official ports from the wider catppuccin org

**Closed** 2024-06-29 01:46 UTC
