### ISSUE TITLE
Global enable doesn't work for GTK

### ISSUE THREAD

**Issue by willbush** [catppuccin/nix#278] opened 2024-07-06 03:12 UTC
The global `catppuccin.enable = true;` (I have [here](https://github.com/willbush/system/blob/832dee36e4eef724102caa8c3ea1879cb887a304/users/will.nix#L70)) doesn't work for gtk:

```sh
~/.config/gtk-4.0
❯ ls -l
total 0
lrwxrwxrwx 1 will users 91 Jul  5 21:59 settings.ini -> /nix/store/lp5d15bq3xz9wdwyhd6w4m7gfzpzhsqm-home-manager-files/.config/gtk-4.0/settings.ini
```

After changing putting explicit: `gtk.catppuccin.enable = true;` in home-manager:

```sh
~/.config/gtk-4.0
❯ sudo nixos-rebuild switch --flake '/home/will/code/system/#blazar'
warning: Git tree '/home/will/code/system' is dirty
building the system configuration...
warning: Git tree '/home/will/code/system' is dirty
trace: warning: will profile: `gtk.catppuccin.enable` and `gtk.catppuccin.gnomeShellTheme` are deprecated and will be removed in a future release.

The upstream port has been archived and support will no longer be provided.
Please see https://github.com/catppuccin/gtk/issues/262

activating the configuration...
setting up /etc...
reloading user units for will...
restarting sysinit-reactivation.target
restarting the following units: home-manager-will.service
the following new units were started: libvirtd.service

~/.config/gtk-4.0
❯ ls -l
total 0
lrwxrwxrwx 1 will users 85 Jul  5 22:02 assets -> /nix/store/33x2c3m1nppkcaw2zjjhw0l5qih0ma6y-home-manager-files/.config/gtk-4.0/assets
lrwxrwxrwx 1 will users 86 Jul  5 22:02 gtk.css -> /nix/store/33x2c3m1nppkcaw2zjjhw0l5qih0ma6y-home-manager-files/.config/gtk-4.0/gtk.css
lrwxrwxrwx 1 will users 91 Jul  5 22:02 gtk-dark.css -> /nix/store/33x2c3m1nppkcaw2zjjhw0l5qih0ma6y-home-manager-files/.config/gtk-4.0/gtk-dark.css
lrwxrwxrwx 1 will users 91 Jul  5 22:02 settings.ini -> /nix/store/33x2c3m1nppkcaw2zjjhw0l5qih0ma6y-home-manager-files/.config/gtk-4.0/settings.ini

~/.config/gtk-4.0
```

How do I migrate away from deprecated usage?

```
trace: warning: will profile: `gtk.catppuccin.enable` and `gtk.catppuccin.gnomeShellTheme` are deprecated and will be removed in a future release.
```

**Comment by pinkcreeper100** [comment] 2024-07-06 06:24
the gtk theme itself is deprecated so is disabled by default

**Comment by willbush** [comment] 2024-07-06 23:40
@vdbe Thanks. I wondering what people are replacing the GTK theme with. I found some discussion [here](https://github.com/catppuccin/nix/issues/196#issuecomment-2184015545) and [here.](https://github.com/catppuccin/nix/pull/206#issuecomment-2183761111), but the entire https://github.com/GradienceTeam org is archived.

**Comment by getchoo** [comment] 2024-07-07 00:31
> The global catppuccin.enable = true; (I have [here](https://github.com/willbush/system/blob/832dee36e4eef724102caa8c3ea1879cb887a304/users/will.nix#L70)) doesn't work for gtk

this is intended -- since as it's deprecated, i would rather not have people automatically opt-in to it nowadays

> How do I migrate away from deprecated usage?

there is no official migration path. you seem to have found some of the previous discussion above, but with gradience gone now...yeah, i'm honestly not sure of a good official *or* unofficial path now :/

in any case: as this is not a bug, closing as WONTFIX

**Closed by getchoo** 2024-07-07 00:30 UTC
