### ISSUE TITLE
Link palette files to graphics editors

### ISSUE THREAD

**Issue by uncenter** [catppuccin/nix#117] opened 2024-04-14 21:49 UTC
I've written https://github.com/uncenter/flake/blob/main/home/apps/inkscape.nix to solve this issue in my personal flake. It downloads the [latest release](https://github.com/catppuccin/palette/releases/latest) assets from [catppuccin/palette](https://github.com/catppuccin/palette) and moves the `gimp/` directory to the `palettes/` directory of Inkscape. I'm not sure what the other configuration locations are for the other graphics programs the release assets support.

**Comment by getchoo** [comment] 2024-04-15 00:03
i would consider this a duplicate of https://github.com/catppuccin/nix/issues/96, as it seems the core request here is to publicly expose our palette source for external reuse. feel free to re-open if i'm mistaken! :)

**Comment by uncenter** [comment] 2024-04-15 01:30
I saw that. I don't think that PR closes this though, as I'm talking about the generated files in the releases rather than the palette data itself.

**Comment by getchoo** [comment] 2024-04-18 16:58
> I'm talking about the generated files in the releases rather than the palette data itself though

ah sorry about that, i see what you mean now

i think this would be better suited to the "port request" category in this case - though i would still be a bit hesitant to call it that as it's not really theming inkscape, gimp, etc. but providing resources to create ports. if there's enough interest i would be happy to accept a PR, but i'd consider this as kinda riding the line of the projects scope. i'll keep this open for a while to get some feedback

**Comment by getchoo** [comment] 2024-11-30 05:21
Closing from lack of interest

**Closed by getchoo** 2024-11-30 05:21 UTC
Labels: port request
